export const ENV = {
  DB_HOST: "DB_HOST",
  DB_PORT: "DB_PORT",
  DB_USERNAME: "DB_USERNAME",
  DB_PASSWORD: "DB_PASSWORD",
  DB_DATABASE: "DB_DATABASE",
  DB_SYNCHRONIZE: "DB_SYNCHRONIZE",
  JWT_SECRET: "JWT_SECRET",
  AUTH_SERVICE_HOST: "AUTH_SERVICE_HOST",
  AUTH_SERVICE_PORT: "AUTH_SERVICE_PORT",
};

export const AUTH_SERVICE_CLIENT = "AUTH_SERVICE_CLIENT";
